services:
  - type: web
    name: ubuyu-marketplace
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 --bind 0.0.0.0:$PORT --timeout 120 'app:create_app(\"production\")'"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
